name: Build Linux (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      target_name:
        required: true
        type: string
      target_arch:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/cpp:ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          mv ./bin/task /usr/local/bin/task

      - name: Setup and build for Linux (via Taskfile)
        run: |
          task setup
          task build
          ls -la build/linux/
        env:
          TARGET_NAME: ${{ inputs.target_name }}
          TARGET_ARCH: ${{ inputs.target_arch }}
          ARTIFACT_NAME: ${{ inputs.artifact_name }}

      - name: Test Linux executable (basic verification)
        run: |
          build/linux/pano-yawfix --version || echo "No version output"
          ldd build/linux/pano-yawfix

      - name: Package Linux binary
        shell: bash
        run: |
          mkdir -p dist/linux
          if [ ! -f "build/linux/pano-yawfix" ]; then
            echo "Error: pano-yawfix not found"
            ls -la build/linux/
            exit 1
          fi
          cp build/linux/pano-yawfix dist/linux/
          if [[ "$GITHUB_REF" =~ refs/tags/v(.+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            VERSION="dev-$(date +%Y%m%d)"
          fi
          cd dist/linux
          mv pano-yawfix "pano-yawfix-v${VERSION}-${{ inputs.target_name }}-${{ inputs.target_arch }}"
          echo "Created files:"
          ls -la
          echo "File size: $(stat -c%s *) bytes"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist/linux/pano-yawfix-*
