name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      ref: ${{ github.ref }}
      target_name: windows
      target_arch: x86_64
      artifact_name: pano-yawfix-windows-x64

  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      ref: ${{ github.ref }}
      target_name: linux
      target_arch: x86_64
      artifact_name: pano-yawfix-linux-x64

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pano-yawfix-windows-x64/pano-yawfix-*
            pano-yawfix-linux-x64/pano-yawfix-*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
